### ISSUE TITLE
Old battles already uploaded

### ISSUE THREAD

**Issue by beanjamin25** [frozenpandaman/s3s#102]
I rarely play turf or private battles, so after a while, those battles get to be older than the last 200, which I believe is all you get from [stat.ink](https://github.com/frozenpandaman/s3s/blob/master/s3s.py#L1362). But while the 200 we get from splatnet are really the last 50 from each mode (turf, anarchy, x battle, private), the 200 we get from stat.ink must just be the last 200 from all modes? In any case, when I use `-r` mode, I constantly get this: 

> Battle already uploaded - \<link to private battle\>
Battle already uploaded - \<link to private battle\>

Is there a way we can directly check battles from each type against stat.ink to prevent this clutter? I guess this would probably involve some changes to the api from stat.ink side though. Or maybe a way to find the oldest recently uploaded battle and not upload battles older than that?

for what its worth, one way to get around this is to delete and reupload the battles, but I dont think this is a desired behavior.

**Comment by frozenpandaman** [comment]
>Is there a way we can directly check battles from each type against stat.ink to prevent this clutter?

Unfortunately not, and Hina has said this won't/can't be added.

>the 200 we get from splatnet are really the last 50 from each mode

This is correct (soon to be 250 once League is added). This is because `specific` is set to `True` here, which makes a query for each type of battle, instead of doing the "latest battles" query:
https://github.com/frozenpandaman/s3s/blob/17921d3d08c4484b8eb204bd41a344c814968ed4/s3s.py#L1384-L1385

>one way to get around this is to delete and reupload the battles

Here's a question: does it _permanently_ fix it when you reupload them, or just temporarily as a stop-gap solution? If I'm thinking about this correctly, I suspect those old private battles might have been uploaded when the UUIDs were generated differently – and thus deleting & reuploading them _could_ be the fix. Can you let me know?

If not, I could add in a [config key](https://github.com/frozenpandaman/s3s/wiki/config-keys) which would change that line of code above to make it so it only checks the latest 50 instead battles (combined) instead of 50 from each time, which should fix this for your case.

Any other ideas @clovervidia?

**Comment by ADeeeee** [comment]
I've noticed s3s.py would retry to upload it perhaps 3 times and have a short break with the already uploaded battles with the debug output, which makes the upload time much longer. 

Maybe we could skip the retries if it's been uploaded. It seems to recognized as upload failed currently.

**Comment by ADeeeee** [comment]
> Here's a question: does it permanently fix it when you reupload them, or just temporarily as a stop-gap solution? If I'm thinking about this correctly, I suspect those old private battles might have been uploaded when the UUIDs were generated differently – and thus deleting & reuploading them could be the fix. Can you let me know?

Absolutely correct. It does FIXES the issue!

**Comment by frozenpandaman** [comment]
Great! @ADeeeee, I think the solution here is just for you to re-upload those few battles, or wait until they get pushed off your "recent 50" lists. I'm sorry for the trouble. This shouldn't be a problem going forward as UUID generation will not be changing, and has been using the new/corrected version for quite some time now.

Let me know to make sure I'm understanding everything correctly & you're in agreement before I close this issue.

**Comment by ADeeeee** [comment]
Yeah, I'm with you. This issue could be closed.

Just BTW, Is it possible to have a "-f / --force" arguement for those already uploaded battles to delete or override the battle on stat.ink? It would be nice without having manually deletion when this case happens, but it's still okay not having this function because it should not often happen and we just need to do it once.

**Comment by frozenpandaman** [comment]
I don't want to allow users to delete (send stat.ink a DELETE request) battles through s3s, but you can easily delete the battles online (click the trash can "Delete" icon in the top right corner of any battle) and then upload it again. The `force_uploads` [config key](https://github.com/frozenpandaman/s3s/wiki/config-keys) may be useful to you too!
