### ISSUE TITLE
SplatNet maintenance error

### ISSUE THREAD

**Issue by ADeeeee** [frozenpandaman/s3s#114]
```
The stored tokens have expired.
Attempting to generate new gtoken and bulletToken...
Got non-JSON response from Nintendo (in api/bullet_tokens step):

Wrote gtoken to config.txt, but could not generate bulletToken.
Is SplatNet 3 undergoing maintenance?
```

The update this for v3.0.0 just stopped the `-M` function with `sys.exit(1)` in line 186 in s3s.py. Shouldn't it goes with retries and keep the script running with `-M`? This should make the script stop everytime after a maintenance of SplatNet.

**Comment by frozenpandaman** [comment]
This only happens if `get_bullet()` fails, in this case:
https://github.com/frozenpandaman/s3s/blob/309640ec7844b700b97b0f13486ea9b6725d19fe/iksm.py#L398-L404

If SplatNet 3 is undergoing maintenance, any number of retries will fail. I _want_ the script to exit here – not for someone's daemon or auto-run setup to potentially go haywire and keep monitoring for battles even while the service is down (not possible in the first place…?) In other words, I don't think the script _should_ keep running with `-M` when every single request will fail repeatedly due to maintenance, and "keep retrying over and over until the service is back up" is also not something I think Nintendo would appreciate, if I had to guess…

SplatNet really only goes offline for a couple hours once every 3 months when it gets updated to support the content from a new season, or when there is downtime/maintenance (also quite rare). I don't think asking people to manually restart the script once every few months at most is asking too much, because "every time" is very infrequently.

If I'm not I understanding your use case or what you're asking here correctly, do let me know.

**Comment by ADeeeee** [comment]
> If I'm not I understanding your use case or what you're asking here correctly, do let me know.
I'm with you, just would like to have a short discuss from my view.

**monitoring mode** for me is like a daemon process in the background (systemd or something) which could output the error and keep running unless user stop it manually.

Maybe a longer duration, ideally half an hour or an hour, between the retries seems pretty okay while the default check time is in every 5 minutes. The maintanence or accident (server, network, client...etc.) usually finished in an hour and I think it's fair to keep the monitoring mode alive. Otherwise, it's kinda making no difference between `-M` and I could just run the script without `-M` in a cronjob no matter what happens and don't need to pay attention to anything which could stop it, too.

Please let me know if any parts of my view is not clear enough.

**Comment by frozenpandaman** [comment]
@ADeeeee That makes sense. How do you deal with updates to s3s? It seems that calls for the same case as this – quitting the script and restarting it. In my view, this should happen pretty often. :)

I'm just worried what will happen if someone has their retry time set to say, 60 seconds, and then it constantly retries that whole time during maintenance… maybe I could just manually add a `sleep()` in there or something, but that doesn't sound like a really great idea since 1) it's unknown how long maintenance will last each time 2) if a user happens to encounter this near the end of maintenance, and the script begins waiting/paused then, it will be paused for much longer than necessary. Isn't it easier to just relaunch it every so often, or shortly after it detects it's been stopped?

**Comment by ADeeeee** [comment]
@frozenpandaman I usually just using crontab within the play time, once in two hours for a row, like s2s before. The reason why I tried the `-M` is avoiding the issue related to expired token (Well, I've been back to old school since there's retries 
 for the token now. #101 and control it with less requests). Maybe I'm just thinking it wrong if it's designed for people who start the script with `-M` before playing the game and stop it right after it, but I'm a lazy guy who just want a background script recording my battles.

> 1) it's unknown how long maintenance will last each time
Of course.
> 2) if a user happens to encounter this near the end of maintenance, and the script begins waiting/paused then, it will be paused for much longer than necessary.
On the other hand, the script could just keep running without a pause, which isn't being annoying to Nintendo at all when the whole SplatNet might just down (timeout) or responsing 503 in mileseconds during maintanence. As an IT engineer, it seems no problem while the service is not even serving or processing the data unless you break it into maintanence.

If so, the script could still go wrong with the error message and don't go `exit()` or `raise()`. It's much simpler when the default checking time is the retry itself. Does it sound good?
