### ISSUE TITLE
Python automatically shuts after entering stat.ink API Token & language

### ISSUE THREAD

**Issue by Cheapd** [frozenpandaman/s3s#118]
Hello. I'm stuck between steps 5 and 6 of the setup instructions. I think I have a similar problem to issue #117 in that python automatically closes when I try to run s3s.py.

I was able to input my API Token, then pressed enter for language, but then I get the message "Please specify whether you want to upload battle results (-nsr) or Salmon Run jobs (-osr). Exiting." after which python immediately closes (I don't have time to input anything). Running it in the command prompt also doesn't allow for further input. I am not yet asked to navigate to a specific URL on Nintendo.com (step 6).

Sorry if there is an easy answer I've missed; I am very new to python.

Thanks :)

**Comment by Cheapd** [comment]
(also I am on windows if this helps)

**Comment by frozenpandaman** [comment]
Instead of just running `python s3s.py` without any flags after it, it's you need to specify which one of those modes you want – whether you want to upload battles or Salmon Run jobs. It will then give a prompt for how many results of the specified type (from 1 to 50) to upload. Alternatively, per the "Usage" section of the readme, if you run `python s3s.py -r` it will check for _all_ unuploaded results (both battles and SR jobs, up to 50 total of each) and upload those.

If you're running s3s for the very first time, though, this probably not what you want. In order to get the most data possible onto stat.ink, before it's gone from SplatNet, i.e. up to 50 battles of _each type_ (TW, Anarchy, X, and Private), you'll want to run `python s3s.py -o` to generate an export and then, once it's done, upload the exported files with `-i`. This isn't the most user-friendly, I admit, but you only have to do it once – and then as long as you run/use s3s regularly you should be good to go.
