### ISSUE TITLE
Automatic Updates?

### ISSUE THREAD

**Issue by bobwithanx** [frozenpandaman/s3s#123]
I’m finding that the cronjobs running the script will stop working periodically. Each time, it appears that the script has an available update. Is there a way to automatically update so uploads can keep happening?

**Comment by zhu2qian1** [comment]
Running `git pull` before uploading might help.
Setting up automatic uploading can be archieved with the script below:

```cron
*/30 * * * * "cd path/to/s3s; git pull; python3 s3s.py -r;" 
```

**Comment by frozenpandaman** [comment]
Sorry for the late reply, was busy with the end of school. Can you do something like this, @bobwithanx?

https://stackoverflow.com/questions/6264596/simulating-enter-keypress-in-bash-script

s3s should update by default if you "press" enter at the prompt.

@zhu2qian1's solution is also a good idea!

Otherwise, if neither if these work for you, I could add a [config key](https://github.com/frozenpandaman/s3s/wiki/config-keys) for this – let me know.

**Comment by frozenpandaman** [comment]
Will close this unless I hear further. :)
