### ISSUE TITLE
Accessing browser SplatNet 3 no longer works

### ISSUE THREAD

**Issue by Ondrashek06** [frozenpandaman/s3s#140]
The guide in the readme no longer works to access SplatNet 3, I get a connection error even with the correct gToken set in the cookie. api.lp1.av5ja.srv.nintendo.net shows the GUI for a split second before showing the error and returning HTTP 400.

**Comment by samuelthomas2774** [comment]
Since 4.0.0-b8c1e0fc (21/08/2023) the home page always attempts to get a second web service token using a custom JavaScript API to check if Tournament Manager is available/get notifications.

It's still possible to use other parts of SplatNet 3 in a browser without the app's JS APIs in the same way by just avoiding the home page, e.g. if you go directly to https://api.lp1.av5ja.srv.nintendo.net/schedule.

Otherwise you need to use an app/browser that implements the app's JavaScript APIs, or you can run something like this before SplatNet 3's JS runs using an extension/breakpoint (not tested; this also means you don't need to set a cookie):

```js
(() => {
    // "web service token" and "game web token" is the same thing
    const token = 'your web service token';

    window.requestGameWebToken = function () {
        Promise.resolve().then(() => window.onGameWebTokenReceive?.call(null, token));
    };
})();
```

(Copied this mostly from stuff I wrote on Discord.)

**Comment by frozenpandaman** [comment]
I became aware of this a few days ago with the SplatNet update but have been super busy, so I haven't gotten around to updating to readme yet or looking into it myself. Thanks for the info, @samuelthomas2774! Will be addressed soon.

**Comment by frozenpandaman** [comment]
There's a new guide up at https://github.com/frozenpandaman/s3s/wiki/in%E2%80%90browser-splatnet-3 for accessing SplatNet 3. I wrote a [userscript](https://gist.github.com/frozenpandaman/8cd8e66757d3478f3aa3839a38ddaa1e) to prompt users for their `gtoken` & then run @samuelthomas2774's code above when the homepage is loaded. I've updated the readme as well.

Thanks, @Ondrashek06 – and you too, Sam, again!
