### ISSUE TITLE
[Enhancement] Allow local storing of Side Order runs

### ISSUE THREAD

**Issue by VGmaster670** [frozenpandaman/s3s#173]
While stat.ink has no plans to support Side Order (see fetus-hina/stat.ink#1262), it would still be nice to able to save our Side Order runs permanently if someone ever makes an app for it (I imagine Splatnet 3 only stores your last 50 runs or so), if not simply on our computers

**Comment by frozenpandaman** [comment]
I'm open to it! I haven't completed SO yet and think it's unlikely that I will due to disinterest of mediocre grind-y roguelites (sorry, Nintendo) – so I'm probably not going to be the one to add in the feature flag or the endpoint requests, as I'll have no way of testing it myself or accessing the screens that SplatNet/NSO recently added for it.

I had this thought too, though, and a few people have expressed interest in making (web)apps, namely @ragadeeshu (see https://github.com/ragadeeshu/alterna-freshness-league, which I was reminded of and thus asked him about this a few days ago). @slushiegoose mentioned the idea as well. Feel free to make a PR or discuss further here!

**Comment by niyari** [comment]
At the same time, we also need to solve the problem of very slow delivery of offline played results.
However, this is outside the scope of s3s.

**Comment by frozenpandaman** [comment]
If anyone wants to add this as a PR, or discuss it further here, please do feel free. For now, I'll be closing this issue as I don't see it as a feature/enhancement that I'll be developing myself.
