### ISSUE TITLE
When should we hope to see s3s.py in the repo?

### ISSUE THREAD

**Issue by JMHAVANCE** [frozenpandaman/s3s#2]
I want to start tracking my Splatoon3 progress right away!

=]

**Comment by frozenpandaman** [comment]
Tonight! Just gotta get my hands on a copy of the game when it comes out here (three hours!!) :D

I'd say 85% of it is written and ready to go, just have to do final checks before adding the code and make sure everything works.

However, note that stat.ink doesn't support Splatoon 3 battles yet. (Actually, you can upload stuff, but it's not visible anywhere.) @fetus-hina's working on it. :) For now, s3s will just support saving your battle results JSON to a local file on your computer, which can later be uploaded to be shown on the site once support is there. This is just v0.0.1 after all!

Also note that Salmon Run support won't be there in these early stages, and certain stuff like gear recognition, scoreboard images and sorting, etc. might take a bit too. Pre-packaged executables won't be available for a while since there will be a _lot_ of updates in a short amount of time in this alpha phase, so just pull the latest update from the command line whenever you can.

Thanks for your excitement!!

**Comment by frozenpandaman** [comment]
OK, update, a _lot_ has changed and the structure of how the backend of how SplatNet 3 works is decently more complicated, and a lot more… well, annoying. Nothing impossible, but definitely annoying. A lot less code is able to be reused from last time.

Token/cookie generation is all done as of now, which is a good thing.

For saving your battles, though, so that they can be uploaded to stat.ink in the hopefully-near-future: There's no JSON endpoint that just lists all your recent results with the full details anymore – you instead need to get a list of all the IDs (which are no longer simple numbers) and then, with that ID, make a separate request for every… single… one. So I need to code that part and the I/O stuff so it can save all of those files to your computer. Not really that complicated, just need to do it and test it!

I need to get to bed now, though, so it'll be a little longer. But I *think* this'll at least be working & uploaded here to the repo in the next 24 hours, if not sooner! (I also want to play the game some… 😅)

If you are very insistent on saving your battle JSONs right now and worried about losing data if you play more than 50 battles before I get s3s updated… well, the [mitmproxy instructions wiki page](https://github.com/frozenpandaman/s3s/wiki/mitmproxy-instructions) is totally updated, so it is possible (not that hard using an emulator via Android Studio, really) to manually grab them. :) …or just screenshot your scoreboard results in the game or SplatNet and use the manual uploader stat.ink will likely have at some point, since that gets most of the important info anyway!

**Comment by frozenpandaman** [comment]
v0.0.1 is now out!!!!! e8f1124

YAAAAAAAAAAYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
