### ISSUE TITLE
Ran into an error

### ISSUE THREAD

**Issue by guigas7** [frozenpandaman/s3s#24]
This happened when running the script during the splatfest

![image](https://user-images.githubusercontent.com/11247506/192077563-f93e7e2f-8302-4dda-acc8-43f4eecff26b.png)

ran it again but it happened again

**Comment by Adrthegamedev** [comment]
I guess i shouldn't've closed #23 then; this seems to be happening to other people as well.

**Comment by guigas7** [comment]
It seems deleting the config.txt solved it

**Comment by frozenpandaman** [comment]
Sorry for the trouble! I… really made this annoying for myself by catching the exception here instead of just letting it error out, which would at least give me some more detail about where it is, haha. Seems like a JSON parsing error, and I'm guessing it's because in the current version it's using an old cookie – v0.1.0 calls `prefetch_checks()` first which should prevent this from happening. I'm waiting on stat.ink to fix a bug to release it.

As @guigas7 suggested, I think deletinng `config.txt` (or deleting your `gtoken` & `bullettoken` from it) should fix things for now.

**Comment by frozenpandaman** [comment]
This is a stat.ink Cloudflare issue, and simply retrying to POST the battle will fix it in the vast majority of cases. I've wrote this into the script – to retry (once) if we run into this error. It's fixed in v0.1.0 which will be out soon.
