### ISSUE TITLE
KeyError: 'vsMode'

### ISSUE THREAD

**Issue by guigas7** [frozenpandaman/s3s#26]
I'm getting this error every time i run the script in -r mode. It worked in -i with the local data. I'm not sure if it could have any relation to #25, since both started with this new update. I've already tried deleting config.txt and trying again but it didn't help.

![image](https://user-images.githubusercontent.com/11247506/192169611-71bd24f9-f48a-4aeb-af3c-54d2a2f1cace.png)

**Comment by frozenpandaman** [comment]
I think this is the annoying thing where `vsHistoryDetail` is sometimes null, so these keys don't exist… not sure what causes it, but I had it in one recent exported results files too.

I can get it fixed soon, but would you mind doing some debugging for me, just in case, @guigas7? Right below line 389 of `s3s.py`…
https://github.com/frozenpandaman/s3s/blob/a45599a32560294cd5d0ef21e93d7a49478145c5/s3s.py#L389

…could you add the following text…
```python
	try:
		mode = battle["vsMode"]["mode"]
	except:
		print(json.dumps(battle))
		sys.exit(0)
```

…and then send me what it exports? If it's too long, feel free to put it in a [Pastebin](https://pastebin.com/) instead of in the comment form here directly.

**Comment by zjiao19** [comment]
I added this try-except code block and got a record with "__typename"=="CoopHistoryDetail". I think it's a salmon run record, so I added the -nsr flag and the issue no longer exists.

**Comment by frozenpandaman** [comment]
Ah, thanks! That helps (and I was able to replicate it on my end too). Should be solved now.

**Comment by OctoFloofy** [comment]
Pasting this here, as asked to 

```
Traceback (most recent call last):
  File "C:\Users\OctoFloofy\Documents\s3s\s3s.py", line 1183, in <module>
    main()
  File "C:\Users\OctoFloofy\Documents\s3s\s3s.py", line 1163, in main
    monitor_battles(which, secs, blackout, test_run)
  File "C:\Users\OctoFloofy\Documents\s3s\s3s.py", line 924, in monitor_battles
    splatfest_match = True if result["vsMode"]["mode"] == "FEST" else False
KeyError: 'vsMode'
```

**Comment by frozenpandaman** [comment]
Fixed in monitoring mode as well now.
