### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by salmonling** [frozenpandaman/s3s#45]
i followed the setup instructions exactly and everything was fine until step 5. after inputting my api key to s3s.py it crashes and doesn't seem to save any data. and now when i try to open it again it still crashes. I deleted everything and redownloaded to try again but that didn't work, any other way to fix this? i'm on windows btw and am trying to use this to access splatnet 3 on my computer

(edit: upon further inspection it seems that the issue is that it won't let me sign in with my nintendo account, is there a way to do so outside of the program?

**Comment by salmonling** [comment]
ended up figuring this out on my own, typed the following into windows powershell

python "C:\Users\(username)\s3s\s3s.py" -o

sorry if this is formatted weird i am not very tech savvy

**Comment by frozenpandaman** [comment]
@salmonling I'm guessing this may be because you had a space in one of the directory names somewhere, so putting it in quotes fixed that. I recommend being located in (via a `cd` command to **c**hange **d**irectory) the `s3s/` directory when you run the script, that way you can just type `python s3s.py ...`
