### ISSUE TITLE
-M crashes when it finds a new salmon run result

### ISSUE THREAD

**Issue by Toufool** [frozenpandaman/s3s#57]
line 1005, in monitor_battles
    outcome = "Success" if result["job_result"]["is_clear"] == True else "Failure"
KeyError: 'job_result'

**Comment by frozenpandaman** [comment]
As a workaround please run it with `-M -nsr`.

**Comment by frozenpandaman** [comment]
This is odd – it ideally shouldn't be querying & setting `result` in the first place since we can't even upload SR data yet, so I'll mitigate this by amending that now… but when `result` is set from the `CoopHistoryDetailQuery` request, it _should_ have a `job_result` key. Have you never played a Salmon Run job, @Toufool?

**Comment by frozenpandaman** [comment]
Actually, no, if you've never played any SR, `salmon_results` will be empty, so the loop won't ever be run. Can you help me debug and confirm you're still getting this error?

**Comment by frozenpandaman** [comment]
OH i'm dumb
