### ISSUE TITLE
Send series progress for every battle 

### ISSUE THREAD

**Issue by spacemeowx2** [frozenpandaman/s3s#64]
https://github.com/frozenpandaman/s3s/blob/ab0b8b3cd2502db84edb0be676b71701cd4cc4aa/s3s.py#L622-L629

Now s3s will only upload challenge progress in the latest game of the series. However this should be able to be calculated using `BankaraBattleHistoriesQuery` query. I think it's easy to implement if you cache the query correctly.

Example:

https://github.com/spacemeowx2/s3si.ts/blob/24384c2a11bb1e54790069197c3770afc7bb7808/src/app.ts#L158-L173

Here are the uploaded battles:

https://stat.ink/@imspace/spl3/4637289e-3de1-4e7b-9fac-93073de1a118
https://stat.ink/@imspace/spl3/cfb1cb58-3075-43d9-a5b5-ae862f4e40ee
https://stat.ink/@imspace/spl3/90ebdca8-1277-4461-ba1c-118f19943855

**Comment by frozenpandaman** [comment]
This is planned: #49

>  QOL: Send series progress for every battle (backwards compute or store state in memory, maybe w/ `-i` & `-r` only)

It probably couldn't work with `-M` mode as battles are sent one-by-one. In your examples, the three battles are sent all in a row (12:19:41, 12:19:42 , 12:19:43)

**Comment by spacemeowx2** [comment]
In my monitor mode, the fetcher is created every poll. So the `BankaraBattleHistoriesQuery` will be refetched and keep updated. I think it works well in monitor mode:

https://stat.ink/@imspace/spl3/cd5603f2-5ac6-4c04-8735-0687b5cf40e0
https://stat.ink/@imspace/spl3/2532b213-b907-41fa-b735-305e8eac1d3e

**Comment by frozenpandaman** [comment]
Yep, it would be possible if I add in something to store the state in memory between battles, that's just not how things are set up now. But it's on the to-do list.

Feel free to try your hand at Python and open a PR to add this, if you're so inclined…! :)

**Comment by frozenpandaman** [comment]
FYI, I'm not sure if this is high up on the priority list. If running the script with `-M` (default frequency: checks for new battles every 5 minutes), the majority of the time this will upload battles one at a time to stat.ink, since that is roughly how long it takes to play one ranked game (the only exception is if one is a draw and thus ends early, or you have two very quick K.O.s – then it will send two, with your 'series progress' only being sent for the second).

FWIW, I played Ranked (Series) tonight for a couple hours and out of 13 battles, it sent for 12 of them. (Not sure why it missed [that one](https://stat.ink/@frozenpandaman/spl3/23e3b0af-0cad-4be1-8d56-92500707ef7b) actually…)

Eventually I'll probably look into adding something to see if it'd be feasible to make it send with `-r` as well, but _I_ personally don't use that mode much so I'm a bit less incentivized, haha, especially when there's other new feature work that I could spend time doing instead.

**Comment by frozenpandaman** [comment]
Idea: Store "memory" of this in `config.txt`.

**Comment by frozenpandaman** [comment]
Series progress is now sent for X Battles. 2b441ad

**Comment by frozenpandaman** [comment]
I don't think I'm going to be implementing this, because it's been a while since this has proposed but: it's not something I'm personally desperate for, it can easily be circumvented by using a lower refresh rate `N` (with `-M`), and I just haven't been playing the game all that much recently (the maps/level design is so bad).

If someone else wants to take a shot, it's a free & open-source project, after all – please feel free!
