### ISSUE TITLE
Existing interface problems

### ISSUE THREAD

**Issue by Sichongzou** [frozenpandaman/s3s#71]
Hello, the author.I have been looking forward to getting a screenshot of my achievements in Statink of Splatonn3. Because the splatnet2statink I used previously supports this, I'm not sure whether you have no development plan in this area or no plan at all in the near future. I saw this in the document in Stat.ink. Emmm, i know this may be troublesome, but please try your best to improve it.
![image](https://user-images.githubusercontent.com/68594934/202360958-8b2c8099-d65a-4e8e-b4f7-07d36b1f3a61.png)
You can find this document here https://github.com/fetus-hina/stat.ink/wiki/Spl3-API:-Post-v3-battle#player-structure

Picture similar to
![image](https://user-images.githubusercontent.com/68594934/202361283-ba666868-799b-4b41-88a1-bc57b141395a.png)

Maybe my translation software is not perfect, but I know you definitely know what I'm talking about.  haha

**Comment by frozenpandaman** [comment]
I'm not sure yet if this will be implemented. There's no "share" function in the app this time around which makes this _significantly_ harder, requiring plugging into the user's web browser via [Selenium](https://www.selenium.dev/) (e.g. headerless Chrome), setting the cookies and headers, navigating to the correct pages in SplatNet, waiting for all the elements to load, then cropping and editing the images… all in all, it will cause s3s to run much slower and is just super difficult to implement and make work for all users.

You can see I started drafting some stuff for it here:
https://github.com/frozenpandaman/s3s/blob/c5aadb520795c7432d4f8cb475719d43b1d4c9bd/s3s.py#L707-L716

However, this isn't likely to get added soon due to the difficulties I described above, and since all the same information is captured in the uploaded info (scoreboard on stat.ink battle result pages) minus the picture of your nameplate and gear. I'd like to try to get it working someday, though, when I have time and all the other more pressing to-do items have been taken care of first!

**Comment by Sichongzou** [comment]
Oh, so the pictures uploaded in splatnet2statink are generated through the sharing function in the APP, rather than being synthesized by ourselves. However, this function is not provided in SplatNet, so you need s3s to synthesize it by themselves?

**Comment by frozenpandaman** [comment]
Yep, that's right. The [way s2s did it](https://github.com/frozenpandaman/splatnet2statink/blob/b7194891cc8d14bee8cea63b5dffdf3b88c570cb/splatnet2statink.py#L1106-L1158) was a lot easier, in that you could just send a POST request to a URL and get an image. There's no function like that in SplatNet 3 – you need to screenshot a portion of the webpage yourself.

**Comment by Sichongzou** [comment]
We really need to wait. Maybe Nintendo will launch this feature at some time in the future. Even if the PIL module is used for composition, the running speed of the program will be affected
