### ISSUE TITLE
Feature request: Fetch data for seed checker

### ISSUE THREAD

**Issue by gomtuu** [frozenpandaman/s3s#74]
Would it be possible to add a feature to s3s that would allow it to fetch the data needed for [Lean's seed checker](https://leanny.github.io/splat3seedchecker/#/tutorial)? I'd like to use the seed checker, but I don't want to give my Nintendo auth tokens to a Discord bot.

Thanks!

**Comment by frozenpandaman** [comment]
Sure, I'd be happy to do that! I'll add a flag for it soon. The whole "not wanting to give my auth tokens to a Discord bot" was the whole reason I asked @Leanny about the structure of the JSON, since I didn't want to do that either. 😅 The structure/logic is pretty simple from what I know and I'll try to get around to it shortly.

**Comment by frozenpandaman** [comment]
@gomtuu Enjoy!

Note that this involves a new dependency, `mmh3`, so you'll need to run `pip install -r requirements.txt` again (or just `pip install mmh3`).

**Comment by gomtuu** [comment]
Awesome! It worked!

Thank you!
